name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code
      with:
        fetch_depth: 0
        
    - name: Docker Login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker Image
      run: |
        docker build -t joseinfositio2024/docker-graphql:0.0.2 .
        docker build -t joseinfositio2024/docker-graphql:latest .
    - name: Push Docker Image
      run: |
        docker push joseinfositio2024/docker-graphql:0.0.2
        docker push joseinfositio2024/docker-graphql:latest
